### ISSUE TITLE
Support more tests suites in PR CI

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#104]
Enable the PR CI infrastructure to execute more resource-consuming integration tests.

## Benefits

- QE can use development runners to run more test cases (as in https://github.com/celestian/freeipa/pull/2 )
- ~Test suite can be extended with more tests (especially for nightly testing)~
- ~All resources of "beefy" runners can be utilized (useful in beaker and for future scaling)~

## Tasks

- [x] support multiple topologies #70
- ~review&adjust PR to support job difficulty definition #54, #72~
- [x] add topologies and difficulty definition in config file (all branches)
- [x] update docs: add section about topologies and job complexity
- ~raise minimum requirements for runner (docs, recreate all runners)~
---
- [x] add external_ca test into the test suite
- [ ] analyze the available resources and capacity for adding more tier0 test suites
- [ ] identify candidate test suites for tier0 testing

**Comment by tomaskrizek** [comment]
The scope of this ticket was adjusted and only the capability to define&use additional topologies was added (in #126). Support of executing multiple jobs in parallel (#54) turned out to be a bit more complicated than expected and was dropped from this story.
