### ISSUE TITLE
Improve usability and sustainability of PR CI

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#105]
Make lives of users and developer of PR CI easier by addressing some of the minor issues.

## Benefits

- More usable, stable and robust interface to deal with
- Easier to use and maintain

## Tasks

**Ordered by priority**, not everything has to be done, some of the minor issues may be too difficult to implement and not worth it.

- [x] change `re-run` behavior to only re-run tasks in failed/error state #81, #83 
- [x] bring back logging of py.test's output #76, https://pagure.io/freeipa/issue/7186
- [x] do not require reboot during runner deployment #113 
- [x] update developer documentation (re-run) #93 
- [x] update developer documentation (ansible and vagrant) #97 
- [x] update README.md #107
- [x] unify replica numbering for logs and tests #74 
- [x] properly support hypervizor machines (`vmx` flag needed?) and test updated beaker file #89
- [x] improve help of `prci_test_control.py` #88
- [x] limit the size of systemd journal #53
- [x] move package list to a separate file #106 
- [x] improve cli for create-template-box #98
---
- [ ] runner disk cleanup #27 
- [ ] add a failover storage for logs #71 
- [ ] add informative messages to job status from py.test #17

**Comment by felipevolpone** [comment]
@tomaskrizek don't you think that "Execute tasks in parallel to fully utilize runner" hasn't a high priority on this list too? IMHO it would be after "change re-run behaviour to only re-run..."
