### ISSUE TITLE
Use PR CI infrastructure to run nightly tests

### ISSUE THREAD

**Issue by felipevolpone** [freeipa/freeipa-pr-ci#108]
Even with a global team, there is some window time that the PR CI infrastructure is not used. We could use these hours to run long tests that require a lot of machinery and resources.

## Benefits
* Have a bigger test coverage
* Utilize PR CI hardware resources

## Tasks
- [x] Automate the creation of a PR at night to have the tests ran

## Depends on:
- [x] Support multiple topologies https://github.com/freeipa/freeipa-pr-ci/issues/70
- [ ] Stabilizing the tests, especially fixing https://pagure.io/freeipa/issue/7165

**Comment by tomaskrizek** [comment]
This isn't a primary use case of PR CI and we currently don't have the either the HW resources or the support for this in our infrastructure.

**Comment by f-trivino** [comment]
Nightly regressions are already in place. We close this ticket.
