### ISSUE TITLE
Run tests on rawhide fedora

### ISSUE THREAD

**Issue by felipevolpone** [freeipa/freeipa-pr-ci#109]
Often happens that we have IPA with some errors when running in a fedora rawhide. We could run nightly tests using rawhide fedora and compare the results with the last run. 

## Benefits
* Figure out problems before releases
* Discover when a new version of some dependency breaks IPA

## Tasks
- [ ] Add an option to disable COPR during template creation (PR #138)
- [ ] Add option to always update pkgs (both in mock and system) during provisioning (PR #139)
- [ ] Automate the creation of PRs at night (PR #136)
- [x] Create a fedora rawhide template ([ci-master-frawhide](https://app.vagrantup.com/freeipa/boxes/ci-master-frawhide))
- [ ] Create a tool to compare results and pkgs with previous test run and generate diff in the PR comment (see https://github.com/tomaskrizek/freeipa/pull/35#issuecomment-327547332 for example)
- [ ] Create a tool to open and close PRs (PR #136)

## Depends on
- ~Use PR CI infrastructure to run nightly tests, #108~

**Comment by felipevolpone** [comment]
PoC:
* https://github.com/tomaskrizek/freeipa/pull/35
* https://github.com/tomaskrizek/freeipa-pr-ci/tree/rawhide-nightly

**Comment by tomaskrizek** [comment]
We don't actually need to create a nigthly rawhide template. It's enough to do this once per release (already done for [ci-master-f28](https://app.vagrantup.com/freeipa/boxes/ci-master-f28)). Then, every night, we just update the packages. It's just important not to use our COPR and use clean distro packages.

The most time consuming part would probably be to automate generating diffs of updated packages and broken/fixed tests since last test. I imagine the result could look like https://github.com/tomaskrizek/freeipa/pull/35#issuecomment-327547332

**Comment by tomaskrizek** [comment]
Rawhide testing would allow us to discover issues with released fedora packages early, so let's do this sooner rather than later.

**Comment by rcritten** [comment]
This is a good idea but in my experience in developing in rawhide for the past few months rawhide is very prone to work-stopping package issues. Yes you catch things earlier but this can't be a blocker for accepting patches because it may have nothing to do with the individual patch (or it might).

IMHO rawhide should be only rawhide and not rely on copr repos to make things work.

**Comment by tomaskrizek** [comment]
The plan is to have the rawhide testing independent of the *acceptance* testing before merging PRs. In other words, regular PRs will be tested with stable fedora and then in addition, we'll test the master branch on rawhide (for example nightly).

COPRs should of course be disabled for rawhide, so we're actually testing what's there.

**Comment by felipevolpone** [comment]
This is part of the #108. With nightly tests using fedora rawhide, we could get the errors earlier. As @tomaskrizek said, this kind of test will not run in each PR.

**Comment by Firstyear** [comment]
Yeah, it will be good to find issues with upstream packages like 389 earlier than later. :)

**Comment by felipevolpone** [comment]
JFTR, due to the lack of resources, we are able to run only the current test suites: `external_ca, caless, simple_replication`.
